<?php

/**
 * @file
 * ubl_metadata_synchronization
 *
 */

/**
 * Implements hook_menu().
 */

function ubl_metadata_synchronization_menu() {
  $items = [];

  $items['admin/islandora/tools/ubl_metadata_synchronization'] = [
    'title' => 'UBL metadata synchronization',
    'description' => 'Settings for UBL metadata synchronization.',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['ubl_metadata_synchronization_settings_form'],
    'access arguments' => ['ubl metadata synchronization'],
    'file' => 'includes/form.inc',
  ];
  $items['islandora/object/%islandora_object/manage/syncid'] = [
    'title' => 'Synchronize',
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
    'page callback' => 'drupal_get_form',
    'page arguments' => ['sync_id_editor_form', 2],
    'access arguments' => ['ubl metadata synchronization'],
    'file' => 'includes/form.inc',
  ];

  return $items;
}

/**
 * Implements hook_permission().
 */

function ubl_metadata_synchronization_permission() {
  return [
    'ubl metadata synchronization' => [
      'title' => 'Edit the synchronization settings, ID and synchronize metadata',
    ],
  ];
}
